name: Run Dunamai
description: |
  Use Dunamai to determine a dynamic version from your VCS tags.
  This requires access to Python in the workflow.
branding:
  icon: terminal
  color: purple
inputs:
  install:
    description: |
      Version of Dunamai to install (e.g., "1.13.2").
      Use the default if you don't need a specific version,
      or use "none" if your workflow installs Dunamai by other means.
    required: false
    default: latest
  env-var:
    description: |
      Name of environment variable in which to set the dynamic version.
      If this is empty, no environment variable will be set.
    required: false
    default: ''
  command:
    description: Command to run Dunamai.
    required: false
    default: 'dunamai from any'
  args:
    description: Additional arguments to pass to the command.
    required: false
    default: ''
outputs:
  version:
    description: The dynamic version.
    value: ${{ steps.main.outputs.version }}
runs:
  using: composite
  steps:
    - id: main
      shell: bash
      run: python -m action
      env:
        PYTHONPATH: ${{ github.action_path }}
        INPUT_INSTALL: ${{ inputs.install }}
        INPUT_ENV_VAR: ${{ inputs.env-var }}
        INPUT_COMMAND: ${{ inputs.command }}
        INPUT_ARGS: ${{ inputs.args }}
