on:
  - push
  - pull_request

name: Main

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - uses: actions/checkout@v3
        with:
          # This is necessary so that we have the tags.
          fetch-depth: 0

      - uses: ./
        name: full invocation
        id: full
        with:
          install: '1.13.2'
          env-var: MY_VERSION
          command: dunamai from git
          args: --style pep440
      - if: matrix.os != 'windows-latest'
        run: echo $MY_VERSION from environment variable
      - if: matrix.os == 'windows-latest'
        run: echo $env:MY_VERSION from environment variable
      - run: echo ${{ steps.full.outputs.version }} from outputs

      - uses: ./
        name: minimal invocation
        id: minimal
      - run: echo ${{ steps.minimal.outputs.version }} from outputs

      - uses: ./
        name: invalid VCS
        continue-on-error: true
        with:
          command: dunamai from incorrect
